packages:
  - packages/*
catalogs:
  build:
    '@tailwindcss/postcss': ^4
    tailwindcss: ^4
    tsdown: ^0.11.7
    typescript: ^5.8.2
  frontend:
    '@radix-ui/react-slot': ^1.2.2
    '@tanstack/react-query': ^5.76.1
    '@tanstack/react-table': ^8.21.3
    '@tanstack/react-virtual': ^3.13.9
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    lucide-react: ^0.510.0
    motion: ^12.11.3
    next: ^15.3.2
    next-themes: ^0.4.6
    radix-ui: ^1.4.1
    react: ^19.0.0
    react-day-picker: ^8.10.1
    react-dom: ^19.0.0
    react-error-boundary: ^6.0.0
    react-resizable-panels: ^3.0.2
    sonner: ^2.0.3
    tw-animate-css: ^1.2.9
  lint:
    '@antfu/eslint-config': ^4.13.0
    '@commitlint/config-conventional': ^19.8.0
    eslint: ^9.22.0
    knip: ^5.55.1
    publint: ^0.3.12
  script:
    cheerio: ^1.0.0
    consola: ^3.4.2
    node-html-parser: ^7.0.1
    ofetch: ^1.4.1
    pathe: ^2.0.3
    simple-git: ^3.27.0
    tailwind-merge: ^3.3.0
    tsx: ^4.19.4
  types:
    '@types/node': ^22.15.17
    '@types/react': ^19
    '@types/react-dom': ^19
  workflow:
    nano-staged: ^0.8.0
    simple-git-hooks: ^2.11.1
