packages:
  - packages/*
catalogs:
  build:
    "@tailwindcss/vite": ^4.1.8
    "@tanstack/router-devtools": ^1.120.18
    "@tanstack/router-plugin": ^1.120.18
    "@tanstack/router-vite-plugin": ^1.120.18
    "@vitejs/plugin-react-swc": ^3.9.0
    tailwindcss: ^4
    tsdown: ^0.11.7
    typescript: ^5.8.2
    vite: ^6.3.5
  frontend:
    "@radix-ui/react-slot": ^1.2.3
    "@tanstack/react-query": ^5.76.1
    "@tanstack/react-router": ^1.120.18
    "@tanstack/react-table": ^8.21.3
    "@tanstack/react-virtual": ^3.13.9
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    lucide-react: ^0.510.0
    motion: ^12.11.3
    next: ^15.3.2
    next-themes: ^0.4.6
    radix-ui: ^1.4.1
    react: ^19.0.0
    react-day-picker: ^8.10.1
    react-dom: ^19.0.0
    react-error-boundary: ^6.0.0
    sonner: ^2.0.3
    tw-animate-css: ^1.2.9
  lint:
    "@sxzz/eslint-config": ^7.0.2
    eslint: ^9.22.0
    publint: ^0.3.12
  script:
    concurrently: ^9.1.2
    nano-staged: ^0.8.0
    node-html-parser: ^7.0.1
    quick-lru: ^7.0.1
    simple-git-hooks: ^2.11.1
    tailwind-merge: ^3.3.0
    tsx: ^4.19.4
  server:
    "@hono/node-server": ^1.14.4
    hono: ^4.7.11
  types:
    "@types/node": ^22.15.17
    "@types/react": ^19
    "@types/react-dom": ^19
