/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LatestRouteImport } from './routes/latest'
import { Route as DateRouteImport } from './routes/$date'
import { Route as IndexRouteImport } from './routes/index'

const LatestRoute = LatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const DateRoute = DateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$date': typeof DateRoute
  '/latest': typeof LatestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$date': typeof DateRoute
  '/latest': typeof LatestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$date': typeof DateRoute
  '/latest': typeof LatestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$date' | '/latest'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$date' | '/latest'
  id: '__root__' | '/' | '/$date' | '/latest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DateRoute: typeof DateRoute
  LatestRoute: typeof LatestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/latest': {
      id: '/latest'
      path: '/latest'
      fullPath: '/latest'
      preLoaderRoute: typeof LatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$date': {
      id: '/$date'
      path: '/$date'
      fullPath: '/$date'
      preLoaderRoute: typeof DateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DateRoute: DateRoute,
  LatestRoute: LatestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
