export const GitHubLanguages = {
  'Unknown': 'unknown',
  '1C Enterprise': '1c-enterprise',
  'ABAP': 'abap',
  'ABAP CDS': 'abap-cds',
  'AGS Script': 'ags-script',
  'ANTLR': 'antlr',
  'API Blueprint': 'api-blueprint',
  'ASL': 'asl',
  'ASP.NET': 'asp.net',
  'ATS': 'ats',
  'ActionScript': 'actionscript',
  'Ada': 'ada',
  'Agda': 'agda',
  'Alloy': 'alloy',
  'Alpine Abuild': 'alpine-abuild',
  'Altium Designer': 'altium-designer',
  'AngelScript': 'angelscript',
  'Apex': 'apex',
  'Apollo Guidance Computer': 'apollo-guidance-computer',
  'AppleScript': 'applescript',
  'Arc': 'arc',
  'AspectJ': 'aspectj',
  'Assembly': 'assembly',
  'Astro': 'astro',
  'Asymptote': 'asymptote',
  'Augeas': 'augeas',
  'AutoHotkey': 'autohotkey',
  'AutoIt': 'autoit',
  'Awk': 'awk',
  'BASIC': 'basic',
  'Ballerina': 'ballerina',
  'Bash': 'bash',
  'Batchfile': 'batchfile',
  'Berry': 'berry',
  'BibTeX': 'bibtex',
  'Bicep': 'bicep',
  'Bison': 'bison',
  'BitBake': 'bitbake',
  'Blade': 'blade',
  'BlitzBasic': 'blitzbasic',
  'BlitzMax': 'blitzmax',
  'Bluespec': 'bluespec',
  'Boo': 'boo',
  'Boogie': 'boogie',
  'Brainfuck': 'brainfuck',
  'Brightscript': 'brightscript',
  'C': 'c',
  'C#': 'c%23',
  'C++': 'c%2B%2B',
  'COBOL': 'cobol',
  'CSS': 'css',
  'CSV': 'csv',
  'CWeb': 'cweb',
  'Cadence': 'cadence',
  'Cairo': 'cairo',
  'CameLIGO': 'cameligo',
  'Cap\'n Proto': 'capn-proto',
  'CartoCSS': 'cartocss',
  'Ceylon': 'ceylon',
  'Chapel': 'chapel',
  'Charity': 'charity',
  'ChucK': 'chuck',
  'Cirru': 'cirru',
  'Clarion': 'clarion',
  'Clean': 'clean',
  'Click': 'click',
  'Clojure': 'clojure',
  'Closure Templates': 'closure-templates',
  'Cloud Firestore Security Rules': 'cloud-firestore-security-rules',
  'CoNLL-U': 'conll-u',
  'CodeQL': 'codeql',
  'CoffeeScript': 'coffeescript',
  'ColdFusion': 'coldfusion',
  'ColdFusion CFC': 'coldfusion-cfc',
  'Common Lisp': 'common-lisp',
  'Common Workflow Language': 'common-workflow-language',
  'Component Pascal': 'component-pascal',
  'Cool': 'cool',
  'Coq': 'coq',
  'Crystal': 'crystal',
  'Cuda': 'cuda',
  'Curry': 'curry',
  'Cycript': 'cycript',
  'D': 'd',
  'DIGITAL Command Language': 'digital-command-language',
  'DM': 'dm',
  'DNS Zone': 'dns-zone',
  'DTrace': 'dtrace',
  'Dafny': 'dafny',
  'Dart': 'dart',
  'DataWeave': 'dataweave',
  'Dhall': 'dhall',
  'Dockerfile': 'dockerfile',
  'Dogescript': 'dogescript',
  'Dylan': 'dylan',
  'E': 'e',
  'ECL': 'ecl',
  'ECLiPSe': 'eclipse',
  'EJS': 'ejs',
  'EQ': 'eq',
  'Eiffel': 'eiffel',
  'Elixir': 'elixir',
  'Elm': 'elm',
  'Emacs Lisp': 'emacs-lisp',
  'EmberScript': 'emberscript',
  'Erlang': 'erlang',
  'F#': 'f%23',
  'F*': 'f*',
  'FLUX': 'flux',
  'Factor': 'factor',
  'Fancy': 'fancy',
  'Fantom': 'fantom',
  'Faust': 'faust',
  'Forth': 'forth',
  'Fortran': 'fortran',
  'FreeMarker': 'freemarker',
  'Frege': 'frege',
  'G-code': 'g-code',
  'GAML': 'gaml',
  'GAMS': 'gams',
  'GAP': 'gap',
  'GCC Machine Description': 'gcc-machine-description',
  'GDB': 'gdb',
  'GDScript': 'gdscript',
  'GLSL': 'glsl',
  'Game Maker Language': 'game-maker-language',
  'Genie': 'genie',
  'Genshi': 'genshi',
  'Gherkin': 'gherkin',
  'Glyph': 'glyph',
  'Go': 'go',
  'Golo': 'golo',
  'Gosu': 'gosu',
  'Grace': 'grace',
  'Grammatical Framework': 'grammatical-framework',
  'GraphQL': 'graphql',
  'Groovy': 'groovy',
  'HTML': 'html',
  'Hack': 'hack',
  'Haml': 'haml',
  'Handlebars': 'handlebars',
  'Harbour': 'harbour',
  'Haskell': 'haskell',
  'Haxe': 'haxe',
  'HiveQL': 'hiveql',
  'HolyC': 'holyc',
  'Hy': 'hy',
  'HyPhy': 'hyphy',
  'IDL': 'idl',
  'IGOR Pro': 'igor-pro',
  'INI': 'ini',
  'Idris': 'idris',
  'Inform 7': 'inform-7',
  'Inno Setup': 'inno-setup',
  'Io': 'io',
  'Ioke': 'ioke',
  'Isabelle': 'isabelle',
  'J': 'j',
  'JFlex': 'jflex',
  'JSONiq': 'jsoniq',
  'Java': 'java',
  'JavaScript': 'javascript',
  'Jison': 'jison',
  'Julia': 'julia',
  'Jupyter Notebook': 'jupyter-notebook',
  'KRL': 'krl',
  'Kotlin': 'kotlin',
  'LFE': 'lfe',
  'LLVM': 'llvm',
  'LOLCODE': 'lolcode',
  'LSL': 'lsl',
  'LabVIEW': 'labview',
  'Lasso': 'lasso',
  'Lean': 'lean',
  'Lex': 'lex',
  'LilyPond': 'lilypond',
  'Limbo': 'limbo',
  'Liquid': 'liquid',
  'LiveScript': 'livescript',
  'Logos': 'logos',
  'Logtalk': 'logtalk',
  'LookML': 'lookml',
  'Lua': 'lua',
  'M': 'm',
  'M4': 'm4',
  'M4Sugar': 'm4sugar',
  'MATLAB': 'matlab',
  'MAXScript': 'maxscript',
  'MLIR': 'mlir',
  'MQL4': 'mql4',
  'MQL5': 'mql5',
  'Makefile': 'makefile',
  'Markdown': 'markdown',
  'Mercury': 'mercury',
  'Metal': 'metal',
  'Mirah': 'mirah',
  'Modelica': 'modelica',
  'Modula-2': 'modula-2',
  'Modula-3': 'modula-3',
  'Module Management System': 'module-management-system',
  'Monkey': 'monkey',
  'Moocode': 'moocode',
  'MoonScript': 'moonscript',
  'Nemerle': 'nemerle',
  'NetLinx': 'netlinx',
  'NetLogo': 'netlogo',
  'NewLisp': 'newlisp',
  'Nim': 'nim',
  'Nit': 'nit',
  'Nix': 'nix',
  'Nu': 'nu',
  'OCaml': 'ocaml',
  'ObjectScript': 'objectscript',
  'Objective-C': 'objective-c',
  'Objective-C++': 'objective-c%2B%2B',
  'Objective-J': 'objective-j',
  'Odin': 'odin',
  'Omgrofl': 'omgrofl',
  'Opal': 'opal',
  'OpenCL': 'opencl',
  'OpenEdge ABL': 'openedge-abl',
  'OpenQASM': 'openqasm',
  'OpenSCAD': 'openscad',
  'Ox': 'ox',
  'Oxygene': 'oxygene',
  'Oz': 'oz',
  'P4': 'p4',
  'PDDL': 'pddl',
  'PHP': 'php',
  'PLSQL': 'plsql',
  'PLpgSQL': 'plpgsql',
  'POV-Ray SDL': 'pov-ray-sdl',
  'Pan': 'pan',
  'Papyrus': 'papyrus',
  'Parrot': 'parrot',
  'Pascal': 'pascal',
  'Pawn': 'pawn',
  'Perl': 'perl',
  'PicoLisp': 'picolisp',
  'Pike': 'pike',
  'PogoScript': 'pogoscript',
  'Pony': 'pony',
  'PostScript': 'postscript',
  'PowerBuilder': 'powerbuilder',
  'PowerShell': 'powershell',
  'Processing': 'processing',
  'Prolog': 'prolog',
  'Propeller Spin': 'propeller-spin',
  'Puppet': 'puppet',
  'PureBasic': 'purebasic',
  'PureScript': 'purescript',
  'Python': 'python',
  'Q#': 'q%23',
  'QML': 'qml',
  'Qt Script': 'qt-script',
  'R': 'r',
  'RAML': 'raml',
  'RDoc': 'rdoc',
  'REALbasic': 'realbasic',
  'REXX': 'rexx',
  'RPC': 'rpc',
  'RUNOFF': 'runoff',
  'Racket': 'racket',
  'Ragel': 'ragel',
  'Raku': 'raku',
  'Rascal': 'rascal',
  'Reason': 'reason',
  'Rebol': 'rebol',
  'Red': 'red',
  'Redcode': 'redcode',
  'Ruby': 'ruby',
  'Rust': 'rust',
  'SAS': 'sas',
  'SCSS': 'scss',
  'SMT': 'smt',
  'SPARQL': 'sparql',
  'SQF': 'sqf',
  'SQL': 'sql',
  'SQLPL': 'sqlpl',
  'Scala': 'scala',
  'Scheme': 'scheme',
  'Scilab': 'scilab',
  'Self': 'self',
  'Shell': 'shell',
  'Shen': 'shen',
  'Slash': 'slash',
  'Slice': 'slice',
  'Smalltalk': 'smalltalk',
  'Solidity': 'solidity',
  'SourcePawn': 'sourcepawn',
  'Squirrel': 'squirrel',
  'Stan': 'stan',
  'Standard ML': 'standard-ml',
  'Starlark': 'starlark',
  'Stata': 'stata',
  'SuperCollider': 'supercollider',
  'Swift': 'swift',
  'SystemVerilog': 'systemverilog',
  'TLA': 'tla',
  'TSQL': 'tsql',
  'TSX': 'tsx',
  'TXL': 'txl',
  'Tcl': 'tcl',
  'Tcsh': 'tcsh',
  'TeX': 'tex',
  'Terra': 'terra',
  'Turing': 'turing',
  'TypeScript': 'typescript',
  'Unified Parallel C': 'unified-parallel-c',
  'Unix Assembly': 'unix-assembly',
  'Uno': 'uno',
  'UnrealScript': 'unrealscript',
  'V': 'v',
  'VBA': 'vba',
  'VBScript': 'vbscript',
  'VCL': 'vcl',
  'VHDL': 'vhdl',
  'Vala': 'vala',
  'Verilog': 'verilog',
  'Vim Script': 'vim-script',
  'Visual Basic .NET': 'visual-basic-net',
  'Volt': 'volt',
  'Vue': 'vue',
  'WebAssembly': 'webassembly',
  'WebIDL': 'webidl',
  'Wollok': 'wollok',
  'X10': 'x10',
  'XC': 'xc',
  'XML': 'xml',
  'XProc': 'xproc',
  'XQuery': 'xquery',
  'XS': 'xs',
  'XSLT': 'xslt',
  'Xojo': 'xojo',
  'Xtend': 'xtend',
  'YAML': 'yaml',
  'YARA': 'yara',
  'YASnippet': 'yasnippet',
  'Yacc': 'yacc',
  'Yul': 'yul',
  'ZAP': 'zap',
  'ZIL': 'zil',
  'Zeek': 'zeek',
  'ZenScript': 'zenscript',
  'Zephir': 'zephir',
  'Zig': 'zig',
  'Zimpl': 'zimpl',
} as const

export type GitHubLanguage = keyof typeof GitHubLanguages
export type GitHubLanguageValue = (typeof GitHubLanguages)[GitHubLanguage]

export function getLanguageUrlParam(language: GitHubLanguage): string {
  return GitHubLanguages[language] || encodeURIComponent(language.toLowerCase())
}

export function isValidGitHubLanguage(language: string): language is GitHubLanguage {
  return language in GitHubLanguages
}
