name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check_commit_message:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    outputs:
      should_run_ci: ${{ steps.check.outputs.should_run_ci }}
    steps:
      - id: check
        run: |
          commit_message="${{ github.event.head_commit.message }}"
          skip_pattern='(\[no ci\]|\[skip ci\]|\[ci skip\]|\[skip actions\]|Update trending repositories)'
          if [[ ! "$commit_message" =~ $skip_pattern ]]; then
            echo "should_run_ci=true" >> $GITHUB_OUTPUT
          else
            echo "should_run_ci=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: [check_commit_message]
    if: needs.check_commit_message.outputs.should_run_ci == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 10.6.3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm build
