name: Scrape Trending Repositories

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
      - uses: pnpm/action-setup@v3
        with:
          version: 10.6.3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Run scraper and commit changes
        run: |
          pnpm start
          if git diff --quiet --exit-code; then
            echo "No changes detected."
          else
            echo "Changes detected. Committing and pushing..."
            git add .
            git commit -m "Update trending repositories" -m "[skip ci]"
            git push origin master
          fi
